# Generated by Django 5.2.3 on 2025-07-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushsubscription',
            name='endpoint',
            field=models.URLField(max_length=1000),
        ),
    ]
