# Generated by Django 5.2.3 on 2025-06-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAmber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_desaparecido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_ubicacion', models.CharField(max_length=255)),
                ('fecha_desaparicion', models.DateField()),
                ('hora_desaparicion', models.TimeField()),
                ('numero_reporte', models.CharField(blank=True, editable=False, max_length=50)),
                ('imagen', models.ImageField(upload_to='alertas_imagenes/')),
                ('estatura', models.CharField(max_length=50)),
                ('contextura', models.CharField(max_length=50)),
                ('tipo_cabello', models.CharField(max_length=50)),
                ('color_cabello', models.CharField(max_length=50)),
                ('color_ojos', models.CharField(max_length=50)),
                ('color_piel', models.CharField(max_length=50)),
                ('señas_particulares', models.CharField(blank=True, max_length=255)),
                ('otros_detalles', models.CharField(blank=True, max_length=25)),
                ('activa', models.BooleanField(default=True, editable=False)),
            ],
        ),
    ]
